language: ruby

services:
  - docker

os: windows

before_install:
  - docker-compose up --build -d

script:
  - docker-compose exec web rails db:create
  - docker-compose exec web rails db:migrate
  - docker-compose exec web rails test